### ISSUE TITLE
Change Font Size

### ISSUE THREAD

**Issue by odesey** [sonaye/react-native-micro-animated-button#3]
Is there anyway to customize the font size, color for the buttons?

Thanks.

**Comment by sonaye** [comment]
Yes, please take a look at the [definition] to find a complete list of the props. To customize the label you can use `labelStyle`, to customize the size if you are using an icon you can use `iconSize`, to customize the colors, well there are many props available depending on the behavior of your button, take a look at the examples to find your match.

**Comment by odesey** [comment]
Got it, thanks!
