### ISSUE TITLE
question/feature request: how to animate a button background between disabled to enabled state

### ISSUE THREAD

**Issue by gianpaj** [sonaye/react-native-micro-animated-button#7]
Some like Trello:

![gif](https://media.giphy.com/media/39vf7l1joWYFH86rzz/giphy.gif)

**Comment by sonaye** [comment]
```javascript
<Btn disabled={this.state.disabled} />
```

Take a look at the list of available props for any customization.

**Comment by gianpaj** [comment]
Thanks but there is no animation or transition when the boolean variable is flipped. It immediately changes the background color.
Does that make sense?

```jsx
import AnimButton from 'react-native-micro-animated-button';
import { Button } from 'react-native';

//...

<AnimButton
  disabled={this.state.disabled}
  label="Disabled Button"
/>
<Button
  onPress={() =>
    this.setState(prevState => ({
      disabled: !prevState.disabled,
    }))
  }
  title="toggle"
/>
```

![gif](https://media.giphy.com/media/4bkzKrieRwG5GBSp8x/giphy.gif)

**Comment by sonaye** [comment]
You can utilize the `style` prop and `Animated`.

```javascript
import React, { Component } from 'react';
import { Animated, View } from 'react-native';

import Btn from 'react-native-micro-animated-button';

export default class App extends Component {
  state = { disabled: true };

  animated = new Animated.Value(0);

  backgroundColor = this.animated.interpolate({
    inputRange: [0, 1],
    outputRange: ['#d8d8d8', '#007aff']
  });

  toggle = () => {
    const { disabled } = this.state;
    this.setState({ disabled: !disabled }, () =>
      Animated.spring(this.animated, { toValue: disabled ? 1 : 0 }).start()
    );
  };

  render() {
    return (
      <View style={{ alignItems: 'center', flex: 1, justifyContent: 'center' }}>
        <Btn
          disabled={this.state.disabled}
          foregroundColor="#ffffff"
          label="Button"
          style={{ backgroundColor: this.backgroundColor, borderWidth: 0 }}
        />

        <Btn label="Toggle" onPress={this.toggle} static />
      </View>
    );
  }
}
```

**Comment by gianpaj** [comment]
Thanks a lot! that helped the animation I wanted.

I had to write some logic to when to toggle between the two states inside the `componentWillUpdate()` because it depends if, for example, a password input field is empty or not.

but now works! thanks again 🎉

**Comment by sonaye** [comment]
You don't need `componentWillUpdate` for that, if what you are trying to implement is your gif I mean, can you share your code?

**Comment by gianpaj** [comment]
Of course! This is my first react and react native app so I'm sure I'm not doing somethings "right" 😊 

here is the gist:
https://gist.github.com/gianpaj/dd81d26190d49ee77ff33c0e8f602244

**Comment by sonaye** [comment]
Actually that looks good to me, it's not how I would do it but it does the job. I would move all the `componentWillUpdate` logic to to a custom handler attached to `onChangeText` of the inputs. Also, it's best to not create new functions in `render()` (they get created with every render), instead move them out and reference them as `this.myFunction`.

**Comment by gianpaj** [comment]
cool thanks. That's better yes.

when you say `best not to create new functions in render()`, do you mean like this line?
https://gist.github.com/gianpaj/dd81d26190d49ee77ff33c0e8f602244#file-anim-button-from-input-fields-js-L81

btw I shared this project with the REact native facebook group :)

**Comment by sonaye** [comment]
Lines 59, 65, 68 and 75, you can read about it [here](https://reactjs.org/docs/faq-functions.html#arrow-function-in-render), and thanks!

**Comment by sonaye** [comment]
The package now supports this feature out of the box in 0.0.17.

**Comment by gianpaj** [comment]
amazing stuff! are you looking for a job btw? 😄

**Comment by sonaye** [comment]
Depends on the job, reach out to me on https://abcd.sa.
